// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dwzxrbgsyzomspmtkeho.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR3enhyYmdzeXpvbXNwbXRrZWhvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDczMzQyNjEsImV4cCI6MjA2MjkxMDI2MX0.JKIxy4td31rEOxbM4LjikSYvVYiP2sUNH4gdIiNIihw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);